name: al_3qed
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  # google_places_flutter: ^2.0.6
  get: ^4.6.5
  # http: ^1.1.0
  dio: ^4.0.0
  eva_icons_flutter: ^3.1.0
  empty_widget: ^0.0.5
  form_field_validator: ^1.1.0
  skeletons: ^0.0.3
  flutter_spinkit: ^5.2.0
  # awesome_notifications: ^0.7.5-dev.3
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  intl_phone_field: ^3.1.0
  cached_network_image: ^3.2.3
  pin_code_fields: ^8.0.1
  font_awesome_flutter: ^10.4.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.6
  # like_button: ^2.0.5
  # i18n_extension: ^9.0.2
  ndialog: ^4.3.0
  overlay_support: ^2.1.0
  # pull_to_refresh: ^2.0.0
  image_picker: ^1.0.2
  # flutter_share: ^2.0.0
  datetime_picker_formfield_new: ^2.1.0
  url_launcher: ^6.1.11
  # colorize_text_avatar: ^1.0.2
  # carousel_slider: ^4.2.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  # flutter_slidable: ^3.0.0
  # geolocator: ^10.0.0
  # geocoding: ^2.1.0
  # timeago: ^3.5.0
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  # flutter_native_splash: ^2.3.2
  photo_view: ^0.14.0
  intl: ^0.18.0
  flutter_screenutil: ^5.9.0
  # google_maps_flutter: ^2.4.0
  flutter_image_compress: ^2.0.3
  # day_night_time_picker: ^1.2.0+2
  image_cropper: ^5.0.0
  bot_toast: ^4.0.4
  extended_phone_number_input: ^1.0.2
  sticky_headers: ^0.3.0+2
  lottie: ^2.6.0
  percent_indicator: ^4.2.3
  hijri: ^3.0.0
  jhijri_picker: ^1.0.1
  skeleton_text: ^3.0.0
  shared_preferences: ^2.2.0
  flutter_pdfview: ^1.3.1
  jhijri: ^1.0.0
  rate: ^0.0.2
  file_picker: ^5.5.0
  path_provider: ^2.0.10
  permission_handler: ^10.4.5
  google_sign_in: ^6.1.5
  firebase_auth: ^4.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/svg/logo.svg"
  # adaptive_icon_background:
# flutter_native_splash:
#   image: assets/splash.png



  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/auth/
    - assets/svg/home/
    - assets/svg/contract/
    - assets/fonts/

  # example:
  fonts:
    - family: BahijTheSansArabic
      fonts:
        - asset: assets/fonts/BahijTheSansArabic.ttf
          weight: 500

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
