// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5x1XU7jIA4f-0lf3OyIUAktLjpz2FEgE',
    appId: '1:662142539680:web:f0ffc63e188263e89cf6c5',
    messagingSenderId: '662142539680',
    projectId: 'contrat-77651',
    authDomain: 'contrat-77651.firebaseapp.com',
    storageBucket: 'contrat-77651.appspot.com',
    measurementId: 'G-RD2LHT3V78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_z7AOyPUiy76MBagpPRibx6GwPoyXiZI',
    appId: '1:662142539680:android:a16edaf874efc5199cf6c5',
    messagingSenderId: '662142539680',
    projectId: 'contrat-77651',
    storageBucket: 'contrat-77651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1Kx-hzlskPQmnTkRa5mUHWcS04F6big',
    appId: '1:662142539680:ios:89c90ade129839919cf6c5',
    messagingSenderId: '662142539680',
    projectId: 'contrat-77651',
    storageBucket: 'contrat-77651.appspot.com',
    iosBundleId: 'com.alqedapp.alqed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz1Kx-hzlskPQmnTkRa5mUHWcS04F6big',
    appId: '1:662142539680:ios:56bdd1bb1851b2e29cf6c5',
    messagingSenderId: '662142539680',
    projectId: 'contrat-77651',
    storageBucket: 'contrat-77651.appspot.com',
    iosBundleId: 'com.example.al3qed.RunnerTests',
  );
}
